server:
  port: 8999

#data source
spring:
    datasource:
        name: ilabservice
        url: jdbc:mysql://127.0.0.1:3306/ilabservice?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000

        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        initialize: false
    jpa:
      hibernate:
        show-sql: true


security:
  jwt:
    refresh-token-exp-time: 600
    token-expiration-time: 300
    security.jwt.token-issuer: ilabservice
    token-signing-key: eKNdtk1qdhYKmjLks618RsXFJ

swagger:
    basepackage: com.ilabservice.intelab
    service:
      name: iLabService
    # 是否启用Swagger 正式生产环境如果需要禁用 设置为false 即可
    show: true

## Swagger 导出文档
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ilabservice.intelab.entity
  typeEnumsPackage: com.ilabservice.intelab.model.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    sqlInjector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


endpoints:
  shutdown:
    graceful:
        # 开启优雅退出
        enabled: true
        # Wait "15" seconds before make a force shutdown
        timeout: 15
        #The time before launch graceful shutdown, the health checker return OUT_OF_SERVICE
        wait: 15